spring:
  application:
    name: order-service

eureka:
  instance:
    prefer-ip-address: true
    hostname: order-service
    lease-renewal-interval-in-seconds: 3
    # ?? 15 ??????????? eureka ???????????
    lease-expiration-duration-in-seconds: 15
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8080
